<a href="https://colab.research.google.com/github/RomanBrick/ML-foundations/blob/master/Math_for_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Math for Deep Learning


### NumPy

In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
# One-dimention array 1D
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.size

5

In [5]:
a.shape

(5,)

In [8]:
# two-dimention array 2D
b = np.array([[1,2,4,5,6],[6,5,4,3,6]])
print(b)

[[1 2 4 5 6]
 [6 5 4 3 6]]


In [9]:
b.shape

(2, 5)

In [11]:
# Zeros and Ones
a1 = np.zeros((3,4), dtype="uint32")
a1[0,3] = 42
a1[1,1] = 66
a1

array([[ 0,  0,  0, 42],
       [ 0, 66,  0,  0],
       [ 0,  0,  0,  0]], dtype=uint32)

In [12]:
#Ones
b1 = 11*np.ones((3,1))
b1

array([[11.],
       [11.],
       [11.]])