<a href="https://colab.research.google.com/github/RomanBrick/ML-foundations/blob/master/Math_for_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Math for Deep Learning


### NumPy

In [1]:
import numpy as np
np.__version__

'1.22.4'

In [2]:
# One-dimention array 1D
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.size

5

In [5]:
a.shape

(5,)

### 2D - two-dimention array

In [8]:

b = np.array([[1,2,4,5,6],[6,5,4,3,6]])
print(b)

[[1 2 4 5 6]
 [6 5 4 3 6]]


In [9]:
b.shape

(2, 5)

In [11]:
# Zeros and Ones
a1 = np.zeros((3,4), dtype="uint32")
a1[0,3] = 42
a1[1,1] = 66
a1

array([[ 0,  0,  0, 42],
       [ 0, 66,  0,  0],
       [ 0,  0,  0,  0]], dtype=uint32)

In [12]:
#Ones
b1 = 11*np.ones((3,1))
b1

array([[11.],
       [11.],
       [11.]])

In [15]:
#INdexing
a3 = np.arange(12).reshape((3,4)) 
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
# return entire subarray
a3[1]

array([4, 5, 6, 7])

In [17]:
a3[1] = [44,55,66,77]

In [18]:
a3

array([[ 0,  1,  2,  3],
       [44, 55, 66, 77],
       [ 8,  9, 10, 11]])

In [19]:
# return the first two rows
a3[:2]

array([[ 0,  1,  2,  3],
       [44, 55, 66, 77]])

In [21]:
# taking the first two rows and first three columns
a3[:2,:3]

array([[ 0,  1,  2],
       [44, 55, 66]])

In [23]:
# Reverse the dimentio
a[::-1]

array([5, 4, 3, 2, 1])

### 3D - three-dimention array

In [ ]:

a4 = np.arange(24).reshape((4,3,2))
a4

In [ ]:
a4[1,:,:] = [[11,22],[33,44],[55,66]]
a4

In [ ]:
a4[2,...]=[[99,99],[99,99],[99,99]]
a4

### Reading and Writing to Disk

In [28]:

a5 = np.random.randint(0,5,(3,4))
a5

array([[3, 1, 3, 0],
       [1, 2, 2, 1],
       [0, 2, 1, 1]])

In [29]:
np.save("random.npy",a5)
b5=np.load("random.npy")
b5

array([[3, 1, 3, 0],
       [1, 2, 2, 1],
       [0, 2, 1, 1]])

## SciPy


In [30]:
import scipy
scipy.__version__

'1.10.1'

P-value -  p-value of 0.05 or less is generally considered to be statistically significant, meaning that the results are unlikely to have occurred by chance. A probility near 1 means we have a lot of cinfidence that the two sets are from the same process

In [31]:
# load ttest_ind function from SciPy stats module
# this function take two sets of data and asks question: Do these sets of data have the same average value?
# OR - how strongly can we belive that the same process generated these two sets of data?
from scipy.stats import ttest_ind 
# 
a5 = np.random.normal(0,1,1000)
b5 = np.random.normal(0,0.5,1000)
c5 = np.random.normal(0.1,1,1000)
ttest_ind(a,b)
# Evaluate its result is to look at p-value
# p-value - probility that the two sets would have the measured difference in average value if the came from the same generating process
# P-values are a statistical measure that tells you how likely it is that your results could have happened by chance.
# A p-value of 0.05 or less is generally considered to be statistically significant, meaning that the results are unlikely to have occurred by chance.


<ipython-input-31-39f9b072483b>:5: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  ttest_ind(a,b)


Ttest_indResult(statistic=array([-0.28171808, -0.3509312 , -0.84515425, -0.77151675, -2.53546276]), pvalue=array([0.78944738, 0.73994226, 0.43658806, 0.47526343, 0.0521814 ]))